'''
A class containing constants of the cards. Constants referenced to img location.
Similar to Java Enumerations
'''

class CARDCONSTANTS():
    _file_directory = "resources/images/cards/"
    TEN_C = _file_directory + "10C.png"
    TEN_D = _file_directory + "10D.png"
    TEN_H = _file_directory + "10H.png"
    TEN_S = _file_directory + "10S.png"
    TWO_C = _file_directory + "2C.png"
    TWO_D = _file_directory + "2D.png"
    TWO_H = _file_directory + "2H.png"
    TWO_S = _file_directory + "2S.png"
    THREE_C = _file_directory + "3C.png"
    THREE_D = _file_directory + "3D.png"
    THREE_H = _file_directory + "3H.png"
    THREE_S = _file_directory + "3S.png"
    FOUR_C = _file_directory + "4C.png"
    FOUR_D = _file_directory + "4D.png"
    FOUR_H = _file_directory + "4H.png"
    FOUR_S = _file_directory + "4S.png"
    FIVE_C = _file_directory + "5C.png"
    FOUR_D = _file_directory + "5D.png"
    FOUR_H = _file_directory + "5H.png"
    FOUR_S = _file_directory + "5S.png"
    SIX_C = _file_directory + "6C.png"
    SIX_D = _file_directory + "6D.png"
    SIX_H = _file_directory + "6H.png"
    SIX_S = _file_directory + "6S.png"
    SEVEN_C = _file_directory + "7C.png"
    SEVEN_D = _file_directory + "7D.png"
    SEVEN_H = _file_directory + "7H.png"
    SEVEN_S = _file_directory + "7S.png"
    EIGHT_C = _file_directory + "8C.png"
    EIGHT_D = _file_directory + "8D.png"
    EIGHT_H = _file_directory + "8H.png"
    EIGHT_S = _file_directory + "8S.png"
    NINE_C = _file_directory + "9C.png"
    NINE_D = _file_directory + "9D.png"
    NINE_H = _file_directory + "9H.png"
    NINE_S = _file_directory + "9S.png"
    ACE_C = _file_directory + "AC.png"
    ACE_D = _file_directory + "AD.png"
    ACE_H = _file_directory + "AH.png"
    ACE_S = _file_directory + "AS.png"
    JACK_C = _file_directory + "JC.png"
    JACK_D = _file_directory + "JD.png"
    JACK_H = _file_directory + "JH.png"
    JACK_S = _file_directory + "JS.png"
    KING_C = _file_directory + "KC.png"
    KING_D = _file_directory + "KD.png"
    KING_H = _file_directory + "KH.png"
    KING_S = _file_directory + "KS.png"
    QUEEN_C = _file_directory + "QC.png"
    QUEEN_D = _file_directory + "QD.png"
    QUEEN_H = _file_directory + "QH.png"
    QUEEN_S = _file_directory + "QS.png"
